dist: trusty
language: node_js
node_js:
- stable
script:
- npm test
after_success:
- npm run coveralls
branches:
only: development
notifications:
email:
recipients:
- Yue1095933649@gmail.com
on_success: never
on_failure: always